theme = "hyde"
baseURL = 'https://huigong-dev.github.io/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Hui Gong'
defaultContentLanguageInSubdir = true

googleAnalytics = "UA-212132284-1"


[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.de]
    languageName = "Deutsch"
    weight = 2

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/HuiGong-dev/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/helen-gong-874b7a7a/"}
  ]

  [params]
    description = "Coding and more"

enableGitInfo = true

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'  
