theme = "hyde"
baseURL = 'https://huigong-dev.github.io/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Hui Gong'
defaultContentLanguageInSubdir = true

googleAnalytics = "<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-212132284-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-212132284-1');
</script>
"


[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.de]
    languageName = "Deutsch"
    weight = 2

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/HuiGong-dev/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/helen-gong-874b7a7a/"}
  ]

  [params]
    description = "Coding and more"
